#!/bin/bash

# Set the key file name
key_name="school"

# Set the key size
key_size=4096

# Set the passphrase
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $key_size -f $key_name -P "$passphrase"
